### ISSUE TITLE
Fire events when enter or exit a drag view

### ISSUE THREAD

**Issue by alexlarocca** [hansemannn/titanium-drag-and-drop#3]
In the case someone would like to highlight the view where dropping will occur, the following events will be fired when entering and leaving. 

`
// MARK: UIDragInteractionDelegate

- (nonnull NSArray<UIDragItem *> *)dragInteraction:(nonnull UIDragInteraction *)interaction itemsForBeginningSession:(nonnull id<UIDragSession>)session
{
  NSString *value = [self identifierFromView:interaction.view];

  [self fireEvent:@"drag" withObject:@{ @"identifier": value }];

  UIDragItem *item = [[UIDragItem alloc] initWithItemProvider:[[NSItemProvider alloc] initWithObject:value]];
  item.localObject = value;

  return @[ item ];
}

// MARK: UIDropInteractionDelegate

- (void)dropInteraction:(UIDropInteraction *)interaction sessionDidEnter:(id<UIDropSession>)session
{
    NSString *value = [self identifierFromView:interaction.view];
    [self fireEvent:@"enter" withObject:@{ @"identifier": value }];
}

- (void)dropInteraction:(UIDropInteraction *)interaction sessionDidExit:(id<UIDropSession>)session
{
    NSString *value = [self identifierFromView:interaction.view];
    [self fireEvent:@"exit" withObject:@{ @"identifier": value }];
}

`

**Comment by hansemannn** [comment]
Great idea! Just implemented the events "drag", "dropenter" and "dropexit"!
